version: "3.8"

services:
  firefly_iii_app:
    image: fireflyiii/core
    container_name: firefly_iii_app
    restart: always
    volumes:
      - ../apps/firefly_iii_app/app:/var/www/html/storage/upload
    ports:
      - 80:8080
    depends_on:
      - firefly_iii_db
    env_file: .env
    networks:
     firefly_network:
      ipv4_address: ${FIREFLY_APP_IP}

  firefly_fidi:
    image: fireflyiii/data-importer:latest
    container_name: firefly_fidi_app
    restart: always
    env_file: .fidi.env
    ports:
      - 81:8080
    depends_on:
      - firefly_iii_app
    networks:
     firefly_network:
      ipv4_address: ${FIREFLY_FIDI_IP}

  firefly_iii_db:
    image: mariadb   
    container_name: firefly_iii_db 
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ../apps/firefly_iii_db/app:/var/lib/mysql
    networks:
     firefly_network:
      ipv4_address: ${FIREFLY_DB_IP}

networks:
  firefly_network:
    external: true
